### ISSUE TITLE
New Study Submission: Stark, 2021

### ISSUE THREAD

**Issue by bcstark** [rbcavanaugh/find-aphasia-research#4]
1. Upload an IRB-approved flyer with this submission in jpg format to this post (see attach file below). Please ensure the IRB record number is somewhere on the flyer

![Inner Speech Ad_Project1UpdatedFinal_PWA-friendly (2)](https://user-images.githubusercontent.com/101271837/157467890-695157be-75eb-4b30-bb87-3e18beaace30.png)

2. Fill out the following information

Name of Principal Investigator: Brielle C. Stark
Name of Study/Project: Characterizing inner speech in aphasia
Study start date: 2021
Location (city, state): Bloomington, IN
Country: USA
Study contact person: Brielle C. Stark
Study contact phone: 770-548-7121
Study contact email: bcstark@iu.edu
Institution: Indiana University Bloomington
IRB record number: #10549

**Comment by bcstark** [comment]
![Inner Speech Ad_Project1UpdatedFinal_PWA-friendly (2)](https://user-images.githubusercontent.com/101271837/157468541-4be95397-546d-4eb9-926d-f973a36ac893.jpg)

**Comment by rbcavanaugh** [comment]
done!
