### ISSUE TITLE
New Study Submission: Stark, 2021

### ISSUE THREAD

**Issue by bcstark** [rbcavanaugh/find-aphasia-research#5]
1. Upload an IRB-approved flyer with this submission in jpg format to this post (see attach file below). Please ensure the IRB record number is somewhere on the flyer

![Inner Speech Ad_Project2Updated_PWA-friendly (2) (1) (2)](https://user-images.githubusercontent.com/101271837/157468115-a5a48198-a273-42be-8d21-5bafa9e1661a.png)

2. Fill out the following information

Name of Principal Investigator: Brielle C. Stark
Name of Study/Project: Inner speech as a naming therapy predictor in aphasia
Study start date: 2021
Location (city, state): Bloomington, IN
Country: USA
Study contact person: Brielle C. Stark
Study contact phone: 770-548-7121
Study contact email: bcstark@iu.edu
Institution: Indiana University Bloomington
IRB record number: #12783

**Comment by bcstark** [comment]
![Inner Speech Ad_Project2Updated_PWA-friendly (2) (1) (2)](https://user-images.githubusercontent.com/101271837/157468458-369f14c0-2ca8-41c9-b820-620f46a52261.jpg)

**Comment by rbcavanaugh** [comment]
done!
