### ISSUE TITLE
New Study Submission: [Harrington, 2022]

### ISSUE THREAD

**Issue by rharrin1** [rbcavanaugh/find-aphasia-research#7]
1. Upload an IRB-approved flyer with this submission in jpg format to this post (see attach file below). Please ensure the IRB record number is somewhere on the flyer

2. Fill out the following information

**About the Study**
Name of Principal Investigator: Rachael Harrington
Name of Study/Project: Reading in Aphasia
Study start date (MM/DD/YYYY): 1/1/2020
Anticipated study end date (MM/DD/YYYY): 12/31/2025
Location (city, state): Atlanta, GA
Country: USA
Institution: Georgia State University
[Recruitment_Flyer_Aphasia.pdf](https://github.com/rbcavanaugh/find-aphasia-research/files/9417809/Recruitment_Flyer_Aphasia.pdf)

IRB record number: H21559

**How you want to be contacted**
Study contact person: Rachael Harrington
Study contact phone: 404-413-6219
Study contact email: rharrington2@gsu.edu

**Comment by rbcavanaugh** [comment]
Hi Rachel - this looks great. Thanks for adding your study to the website!

Do you mind adding your IRB record number somewhere on the flyer? This is just an easy way for me to make sure anything I post is IRB approved. 

thanks! Rob

**Comment by rharrin1** [comment]
[RIA_Flyer_IRBNumber.docx](https://github.com/rbcavanaugh/find-aphasia-research/files/9424905/RIA_Flyer_IRBNumber.docx)

See attached! At GSU they don't like to have anything referencing the IRB on the flyer - not sure why.

**Comment by rbcavanaugh** [comment]
done!
